### ISSUE TITLE
Simplify setup

### ISSUE THREAD

**Issue by nickpunt** [nsporillo/GlobalWarming#3]
Right now a lot of specific knowledge is required in order to try GlobalWarming out: 

- compiling Minecraft plugins / java apps
- running Minecraft server & sorting out Minecraft versions
- setting up Spigot
- installing plugin

Searching for guides is time consuming and piecing everything together is difficult even for technical people not familiar with Minecraft server/plugin ecosystem. This is a big barrier to entry to soliciting feedback and refining the product, especially from folks that may have domain knowledge or would deploy this in an educational setting. Possible ways to simplify this are:

- easy way to spin up remote server with plugin installed
- downloadable binaries
- guide for macos/windows/linux on compiling project
- guide for macos/windows/linux on setting up Minecraft with appropriate plugins

**Comment by nsporillo** [comment]
Initial writeup: https://github.com/nsporillo/GlobalWarming/wiki/Developer-Setup-and-Installation

I should add that this project is still very much a WIP as I only began development 3 days ago. I've been making good progress, but there really wont be anything worth testing out for at least a few more days.

**Comment by nsporillo** [comment]
Added more content to the wiki: https://github.com/nsporillo/GlobalWarming/wiki

**Comment by nsporillo** [comment]
Should be all set to close now after https://github.com/nsporillo/GlobalWarming/commit/bbc93e47fc9e5cba2b90d91bbd6a79aade9d37be
