### ISSUE TITLE
Feature request: SqLite support

### ISSUE THREAD

**Issue by SlimeDog** [nsporillo/GlobalWarming#30]
Please support SqLite database.

**Comment by nsporillo** [comment]
I can look into supporting SQLite, however this might take some time to research and implement. Given my upcoming vacation and then new career, I'll accept this issue but also tag it for help wanted. Hoping someone else can help implement it.

**Comment by SlimeDog** [comment]
Thanks. Many open-source plugins have implemented SqLite support. You (or someone) should be able to borrow.

**Comment by nsporillo** [comment]
@SlimeDog Added H2 support on a branch: https://github.com/nsporillo/GlobalWarming/commit/2d5c68b6d7b3c692b7601f1589038c2304279575

SQLite support seemed like a much more intensive upgrade for virtually the same end goal: embedded database support for persistence on reboots.
