### ISSUE TITLE
about papi

### ISSUE THREAD

**Issue by BackWheel** [nsporillo/GlobalWarming#32]
I am using your global warming plugin. The plugin is very creative, but I hope this plugin will support papi, allowing me to display the current world temperature through the scoreboard. Although the plugin already comes with a scoreboard, it doesn't work with my own scoreboard, so I hope you can provide a placeholder for this plugin.

**Comment by nsporillo** [comment]
Sure that is something I'd like to do. I havent added it yet because I was waiting for the community to reach out and ask for integration into their plugins instead of myself trying to know exactly how it's going to be used.

**Comment by nsporillo** [comment]
This has been completed. Thanks!
