### ISSUE TITLE
Vanilla scoreboard mechanics

### ISSUE THREAD

**Issue by KingofAnomaly** [nsporillo/GlobalWarming#33]
Does this plugin have a score that can be manipulated using vanilla minecraft’s Scoreboard commands? If not I feel like implementing this feature could greatly improve the plugin’s customization options.

**Comment by nsporillo** [comment]
Unfortunately not. We use a default scoreboard and if that is disabled, there is no way I know to supply the vanilla minecraft with the variables necessary.

However, we do support Placeholder API tags now if you'd be interested in using something like Featherboard which supports them.
