### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by wishbonewebsites** [nsporillo/GlobalWarming#44]
Server Log:
https://pastebin.com/3kyzt7t5

Minecraft server version : Paper 1.14.4

Plugins Im using:
AdvancedAchievements
ClearLag
CoreProtect
Essentials
EssentialsGeoIP
EssentialsXMPP
GlobalWarrming
GriefPreventionData
ItemJoin
MultiVoteListener
NPCAuctions
PermissionsEx
Variables
Vault
Votifier
WorldEdit
WorldGaurd
bstats

**Comment by omn0mn0m** [comment]
I am also having the same error in Paper 1.15.1 using both Oracle Java build 1.8.0_181-b13 and OpenJDK 64-Bit Server VM 25.232-b09.

Plugins List:
- AdvancedAchievements
- Brewery
- Citizens
- Civs
- CoreProtect
- CraftBook
- CrazyCrates
- DiscordSRV
- Disease
- Essentials
- EssentialsChat
- EssentialsProtect
- EssentialsSpawn
- Jobs
- LuckPerms
- Magic
- mcMMO
- Multiverse-Core
- Multiverse-Inventories
- PetMaster
- Quests
- Runecraft
- SimpleEgg
- Vault
- WorldEdit
- WorldGuard

**Comment by nsporillo** [comment]
This should be resolved with the latest update.
