### ISSUE TITLE
Multi-world: no climate engine

### ISSUE THREAD

**Issue by jdewever** [nsporillo/GlobalWarming#47]
**Describe the bug**
When using multiple worlds, as provided by MultiVerse-Core, the plugin spams that it can not find the climate engine for that world. I've tried to duplicate the files of the default world, renaming them after the new world, but no luck, even after restart.

**To Reproduce**
1. Run the plugin on the default world
2. Create a new world with MultiVerse-core
3. In the console, you see it spamming "[GlobalWarming] Climate engine not found for world: 'test'"

**Expected behavior**
For the plugin to recognise that it has no configuration for that new world, and creates one for it. While the server runs or on startup.

**Screenshots**
A screenshot of the warning-message
https://imgur.com/a/nviWV3K
![image](https://user-images.githubusercontent.com/25122139/74090688-90a94a00-4aae-11ea-9a92-3165fabb3d0b.png)

**Additional context**
Using Multiverse-core v4.1.0
Spigot 1.14.4

**Comment by jdewever** [comment]
This is the screenshot directly uploaded here
![image](https://user-images.githubusercontent.com/25122139/74090683-825b2e00-4aae-11ea-8284-af54b9e7167e.png)

**Comment by nsporillo** [comment]
This should be fixed with the latest changes in https://github.com/nsporillo/GlobalWarming/commit/040222c7cb27f80c6dcf1ecad85ddf930ea06d3f
