### ISSUE TITLE
Sea level will not drop after the temperature drops

### ISSUE THREAD

**Issue by ClayCoffee** [nsporillo/GlobalWarming#48]
**Describe the bug**
Sea level will not drop after the temperature drops

**To Reproduce**
1. Let the temperature rise and the sea level rise
2. Let the temparature drop
3. The sea level won't drop after the temperature drops.

**Expected behavior**
The sea level should drop to the base sea level(y=62).

**Screenshots**
https://s1.ax1x.com/2020/05/09/Y1PGee.png

**Additional context**

**Comment by ClayCoffee** [comment]
I am so confused abot this
My players are complaining!!!

**Comment by nsporillo** [comment]
Should be fixed with the latest version
