### ISSUE TITLE
[Request] Mod Version

### ISSUE THREAD

**Issue by martmists** [nsporillo/GlobalWarming#9]
Adding this as a form of mod (for forge) rather than a plugin, this would be very interesting to use in modpacks, making them more challenging and challenging users to balance out progression, as there could be a config for custom blocks (such as coal generators or boilers) to generate carbon dioxide.

Forge for 1.13 is still in development, but a 1.12 backport and maybe 1.13 version as mod would be amazing to see.

**Comment by nsporillo** [comment]
There is an existing project for forge which accomplishes the same goals as this project. You can find it here: https://github.com/Artem226/MinecraftEcologyMod

I found this project after deciding to create this one for Spigot servers, so while the idea is not unique; this project is all in on adding climate change effects to Spigot servers only.
